spring:
  application:
    name: stream-receiver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: will
    password: test1234

  cloud:
    stream:
      bindings:
        inputProduct:
          destination: exchangeProduct
          group: groupProduct
          consumer:
            partitioned: true
      instanceCount: 2
      instanceIndex: 0

server:
  port: 9044

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/

