spring:
  application:
    name: eureka-consumer

server:
  port: 8082

ribbon:
  eureka:
    enabled: false

eureka-provider:
  ribbon:
    listOfServers: eureka1:8081
#    listOfServers: eureka1:8081,eureka2:8081
