spring:
  application:
    name: e-book-hystrix-turbine-mq

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: will
    password: will1234
#    virtualHost: "/"

server:
  port: 1002

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
