spring:
  application:
    name: e-book-provider

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
