spring:
  application:
    name: zuul-gateway
  zipkin:
    baseUrl: "http://zipkin:9411/"
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
