spring:
  application:
    name: e-book-consumer

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

logging.level.net.will.ebook.consumer.controller.ProductController: DEBUG
