spring:
  application:
    name: e-book-consumer-hystrix-threadpool

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
