spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8761/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 30000
