spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
#  server:
#    enableSelfPreservation: false
#    eviction-interval-timer-in-ms: 60000
