spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: 123456

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://user:123456@eureka2:8761/eureka/
#  server:
#    enableSelfPreservation: false
#    eviction-interval-timer-in-ms: 60000
