spring:
  application:
    name: eureka-server-single

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 90000
