spring:
  application:
    name: e-book-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysql:3306/book-user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
    username: will
    password: test1234

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:3306/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  type-aliases-package: net.will.ebook.user.domain
  mapper-locations: "classpath:/mybatis/net/will/ebook/user/*.xml"
