spring:
  application:
    name: e-book-consumer-hystrix-feign-fallback

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

feign:
  hystrix:
    enabled: true