spring:
  application:
    name: eureka-server
  profiles: eureka1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8761/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 30000

---
spring:
  application:
    name: eureka-server
  profiles: eureka2

server:
  port: 8761

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 60000
