version: '3'
services:
  eureka:
    container_name: eureka
    image: registry-will:5000/eureka-server-single:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    volumes:
      - /data/volume/eureka:/data/logs
    privileged: true
    networks:
      - default
