version: '3'
services:
 elasticsearch:
  container_name: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
  environment:
   - discovery.type=single-node
#   - node.name=es01
#   - cluster.initial_master_nodes=es01
  volumes:
   - /data/volume/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
   - "9200:9200"
   - "9300:9300"
  privileged: true
  networks:
   - default
   
 logstash:
  container_name: logstash
  image: docker.elastic.co/logstash/logstash:7.4.2
  volumes:
#   - /data/volume/logstash/config:/usr/share/logstash/config
   - /data/volume/logstash/pipeline:/usr/share/logstash/pipeline
  ports:
   - "6000:5000"
  privileged: true
  networks:
   - default
   
 kibana:
  container_name: kibana
  image: docker.elastic.co/kibana/kibana:7.4.2
  environment:
   - elasticsearch.hosts=http://elasticsearch:9200
  ports:
   - "5601:5601"
  privileged: true
  networks:
   - default
   
networks:
  default:
    external:
      name: willnet
