spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/will8ug/config'
          searchPaths: '{application}'
#          username: username
#          password: password

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
