version: '3'
services:
  e-book-product:
    container_name: e-book-order
    image: registry-will:5000/e-book-order:0.0.1-SNAPSHOT
    ports:
      - "8085:8085"
    networks:
      - default

networks:
  default:
    external:
      name: willnet
