spring:
  application:
    name: springboot-helloworld
  boot:
    admin:
      client:
        url: http://localhost:8090
        instance:
          service-base-url: http://localhost:8090
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

hello:
  msg: "Hello World!"

---
spring:
  profiles: dev

server:
  port: 9090

logging:
  level:
    net:
      will:
        sbgradlestudy: trace
#  path: output-hello/logs/
  file: logs/springboot-helloworld.log
  pattern:
    # the pattern to console
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
    # the pattern to log file
    file: "%d{yyyy-MM-dd} === [%thread] == %-5level == %logger{50} == %msg%n"

---
spring:
  profiles: test

server:
  port: ${random.int[1024,9999]}