spring:
  application:
    name: springboot-helloworld
  boot:
    admin:
      client:
        url: http://localhost:8090
        instance:
          service-base-url: http://localhost:8090
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

hello:
  msg: "Hello World!"

---
spring:
  profiles: dev

server:
  port: 9090

---
spring:
  profiles: test

server:
  port: ${random.int[1024,9999]}