version: '3'
services:
  e-book-product:
    container_name: config-server
    image: registry-will:5000/config-server:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    networks:
      - default

networks:
  default:
    external:
      name: willnet
