spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/will8ug/config'
          searchPaths: '{application}'
#          username: username
#          password: password

  security:
    basic:
      enabled: true
    user:
      name: user
      password: 123456

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/

logging.level.org.springframework.boot.autoconfigure.security: INFO
