spring:
  application:
    name: e-book-consumer

server:
  port: 8084
  compression:
    enabled: true
    mime-types: text/xml,text/html,text/plain,application/xml,application/json

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

# These settings can be omitted if we have set those of Spring-Boot like server.compression.enabled.
#feign:
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 512
#    response:
#      enabled: true
