spring:
  application:
    name: e-book-consumer-order
  zipkin:
    baseUrl: "http://zipkin:9411/"
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

ribbon:
  MaxAutoRetries: 2
  ConnectTimeout: 3000
  ReadTimeout: 3000
