version: '3'
services:
  e-book-product:
    container_name: e-book-trade
    image: registry-will:5000/e-book-trade:0.0.1-SNAPSHOT
    ports:
      - "8086:8086"
    networks:
      - default

networks:
  default:
    external:
      name: willnet
