spring:
  application:
    name: springboot-helloworld
  boot:
    admin:
      client:
        url: http://localhost:8090
        instance:
          service-base-url: http://localhost:8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

hello:
  msg: "Hello World!"


server:
  port: 9090

