spring:
  application:
    name: springboot-hello-async

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 9090

