spring:
  application:
    name: eureka-consumer

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule