spring:
  application:
    name: e-book-consumer-hystrix

  redis:
    database: 1
    host: redis-server
    port: 6379
    password: pwd
    pool:
      max-active: 100
      max-wait: 3000
      max-idle: 200
      min-idle: 50
      timeout: 600

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

